Repository jakearchibald/svgomg, pull requests merged in 2022-10, with the labels that each got.

#341 Update most dependencies
  .stylelintrc
  gulpfile.js
  package-lock.json
  package.json
  src/js/svgo-worker/index.js
Labels: dependencies

#366 Use `buttons` when possible
  src/index.html
  src/js/page/ui/floating-action-button.js
Labels: a11y

#374 Update CI config
  .github/dependabot.yml
  .github/workflows/ci.yml
  .github/workflows/codeql.yml
Labels: no-squash

#394 Update to SVGO 3.0 and add transform precision option
  package-lock.json
  package.json
  src/changelog.json
  src/config.json
  src/index.html
  src/js/svgo-worker/index.js
Labels: enhancement, dependencies
